### ISSUE TITLE
New version coming up soon? 😉

### ISSUE THREAD

**Issue by kutyel** [turboMaCk/any-dict#17]
Since some new functions were added I was expecting a new **minor release** when you have time! 🙌🏻

**Comment by turboMaCk** [comment]
I need to review the changes one more time before releasing. I might add some more functions if it would be awkward to skip them while providing what was added but I'm not sure if that will be necessary. I think I might get to that over the weekend.

**Comment by turboMaCk** [comment]
2.6.0 is out. I'll also port new functions to any-set where it makes sense for the symmetry between the two libs.
